"""drop roles

Revision ID: 87df1f3d3ea2
Revises: de467eab0e9f
Create Date: 2025-04-18 12:58:26.100309

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87df1f3d3ea2"
down_revision: Union[str, None] = "de467eab0e9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "role",
            postgresql.ENUM("BASIC", "SUBSCRIBER", "ADMIN", name="role"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
