"""phone birth_date are nullable

Revision ID: 48aafc378157
Revises: a80e58f00f4c
Create Date: 2025-04-15 12:35:14.899429

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48aafc378157"
down_revision: Union[str, None] = "a80e58f00f4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("profiles", "phone", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("profiles", "birth_date", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("profiles", "birth_date", existing_type=sa.DATE(), nullable=False)
    op.alter_column("profiles", "phone", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
